config/routes.rb
Rails.application.routes.draw do

  resources :items, :except => [:update] do
    collection do
      get :completed
      get :active
      get :home
    end

    member do
      post :complete
      post :incomplete
    end
  end

  root 'items#home'

end

app/models/item.rb
class Item < ActiveRecord::Base
  validates :task, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all

    render partial: 'list', locals: {items: @items}
  end

  def home
    @items = Item.all
  end

  def completed
    @items = Item.where(:completed => true)
    render partial: 'list', locals: {items: @items}
  end

  def active
    @items = Item.where(:completed => false)
    render partial: 'list', locals: {items: @items}
  end

  def create
    @item = Item.create(item_params)

    render :'_item', layout: false
  end

  def complete
    @item = Item.find(params[:id])
    @item.update(completed: true)

    if params[:from] == 'active'
      redirect_to active_items_path
    else
      redirect_to root_path
    end
  end

  def incomplete
    @item = Item.find(params[:id])
    @item.update(completed: false)

    if params[:from] == 'completed'
      redirect_to completed_items_path
    else
      redirect_to root_path
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    case params[:from]
    when 'completed' then redirect_to completed_items_path
    when 'active' then redirect_to active_items_path
    else redirect_to root_path
    end
  end

  private

  def item_params
    params.require(:item).permit(:task)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<%= form_for :item, url: items_path, html: {class: "newItemForm"} do |f| %>
  <p>
    <%= f.label :task %><br>
    <%= f.text_field :task, id: 'inputField' %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/items/_item.html.erb
<li>
  <%= @item.task %> -
  <%= @item.completed %>
  <%= link_to("Complete", complete_item_path(@item, @item.id), class: "completeButton", :method => 'post') %>
  <%= link_to('Delete', item_path(@item, @item.id), class: "deleteButton", :method => 'delete') %>
</li>

app/views/items/_list.html.erb
<% items.each do |item| %>
  <li><%= item.task %> -
      <%= item.completed %> -
      <% if item.completed %>
        <%= link_to("Undo", incomplete_item_path(item, :from => action_name), class: 'undo', :method => 'post') %>
      <% else %>
        <%= link_to("Complete", complete_item_path(item, :from => action_name), class: 'complete', :method => 'post') %>
      <% end %>
      - <%= link_to('Delete', item_path(item, :from => action_name), class: 'delete', :method => 'delete') %></li>
<% end %>

app/views/items/home.html.erb
<h1>ToDo List</h1>

<%= render 'form' %>

<ul>
  <%= render partial: 'list', locals: {items: @items}, layout: false %>
</ul>

<%= link_to "All", items_path, id: 'sort_none'%>
<%= link_to "Completed", completed_items_path, id: 'sort_complete'%>
<%= link_to "Active", active_items_path, id: 'sort_active'%>

app/views/items/new.html.erb
<h1>New Item</h1>

<

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>